apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-container
        image: azizgmaty/mon-angular-app:21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-svc
spec:
  selector:
    app: angular-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer