apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: angular-app   # Added namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-container
          image: azizgmaty/mon-angular-app:mon-angular-app:21-cea5d70
          ports:
            - containerPort: 80
